version: '3.8'
services:
  app:
    image: app-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: app-proc-c
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production